In [1]:
import os
import numpy as np
import pandas as pd
dataframe=pd.read_csv("C:\\Users\\donjo\\OneDrive\\Desktop\\de.csv", encoding='latin1')
print(dataframe.shape)
print(dataframe.isnull().sum())
dataframe=dataframe.dropna()

(14999, 6)
Unnamed: 0    0
Statement     0
Link          0
Date          0
Source        0
Label         0
dtype: int64


In [2]:
x=dataframe['Statement']
x.shape

(14999,)

In [3]:
y=dataframe['Label']
y

0        False
1        False
2        False
3        False
4        False
         ...  
14994     True
14995    False
14996     True
14997     True
14998     True
Name: Label, Length: 14999, dtype: bool

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.5,random_state=0)
y_train.shape

(7499,)

In [6]:
tfvect = TfidfVectorizer(stop_words='english',max_df=0.7)
tfid_x_train = tfvect.fit_transform(x_train)
tfid_x_test = tfvect.transform(x_test)

In [7]:
print(dataframe.dtypes)

Unnamed: 0     int64
Statement     object
Link          object
Date          object
Source        object
Label           bool
dtype: object


In [8]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)
tfvect = TfidfVectorizer(stop_words='english',max_df=0.7)
tfid_x_train = tfvect.fit_transform(x_train)
tfid_x_test = tfvect.transform(x_test)

In [9]:
#dt
from sklearn import tree
dt_clf=tree.DecisionTreeClassifier(max_depth=10)
dt_clf.fit(tfid_x_train,y_train)
y_pred=dt_clf.predict(tfid_x_test)
dt_clf.score(tfid_x_test,y_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 64.67%


In [10]:
print("train Accu:",dt_clf.score(tfid_x_train,y_train))
print("test Accu:",dt_clf.score(tfid_x_test,y_test))

train Accu: 0.683303171730641
test Accu: 0.6466666666666666


In [11]:
from sklearn.metrics import confusion_matrix,f1_score
confusion_matrix(y_test,y_pred)

array([[2451,  312],
       [1278,  459]], dtype=int64)

In [12]:
f1score = f1_score(y_test,y_pred)
f1score

0.3660287081339713

In [13]:
def fake_news_det2(news):
    input_data = [news]
    vectorized_input_data = tfvect.transform(input_data).toarray()
    prediction = dt_clf.predict(vectorized_input_data)
    print(prediction)
#print(vectorized_input_data)
#print(tfvect.vocabulary_)

In [14]:
fake_news_det2('india is a country')

[False]


In [15]:
#PA
from sklearn.linear_model import PassiveAggressiveClassifier
pa_clf = PassiveAggressiveClassifier(max_iter=90)
pa_clf.fit(tfid_x_train,y_train)
y_pred=pa_clf.predict(tfid_x_test)
pa_clf.score(tfid_x_test,y_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 63.53%


In [16]:
from sklearn.metrics import confusion_matrix,f1_score
confusion_matrix(y_test,y_pred)

array([[1900,  863],
       [ 778,  959]], dtype=int64)

In [17]:
f1score = f1_score(y_test,y_pred)
f1score

0.5389154256813712

In [18]:
def fake_news_det1(news):
    input_data = [news]
    vectorized_input_data = tfvect.transform(input_data)
    prediction = pa_clf.predict(vectorized_input_data)
    print(prediction)

In [19]:
fake_news_det1('india is a country')

[False]


In [22]:
#LR
from sklearn.linear_model import LogisticRegression
lg_clf=LogisticRegression(max_iter=300)
lg_clf.fit(tfid_x_train,y_train)
lg_clf.score(tfid_x_test,y_test)
y_pred=lg_clf.predict(tfid_x_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 69.29%


In [23]:
from sklearn.metrics import confusion_matrix,f1_score
confusion_matrix(y_test,y_pred)

array([[2331,  432],
       [ 950,  787]], dtype=int64)

In [24]:
f1score = f1_score(y_test,y_pred)
f1score

0.5324763193504736

In [25]:
def fake_news_det3(news):
    input_data = [news]
    vectorized_input_data = tfvect.transform(input_data)
    prediction = lg_clf.predict(vectorized_input_data)
    print(prediction)

In [26]:
fake_news_det3('india is a country')

[ True]


In [27]:
#KNN
from sklearn.neighbors import KNeighborsClassifier as KNN
kn_clf=KNN(n_neighbors=5)
kn_clf.fit(tfid_x_train,y_train)
print(kn_clf.score(tfid_x_test,y_test))
y_pred=kn_clf.predict(tfid_x_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

0.6666666666666666
Accuracy: 66.67%


In [28]:
from sklearn.metrics import confusion_matrix,f1_score
confusion_matrix(y_test,y_pred)

array([[2101,  662],
       [ 838,  899]], dtype=int64)

In [29]:
f1score = f1_score(y_test,y_pred)
f1score

0.5451788963007883

In [30]:
def fake_news_det4(news):
    input_data = [news]
    vectorized_input_data = tfvect.transform(input_data)
    prediction = kn_clf.predict(vectorized_input_data)
    print(prediction)

In [31]:
fake_news_det4('india is a country')

[ True]


In [32]:
#SVM
from sklearn.svm import SVC
sv_clf=SVC()
sv_clf.fit(tfid_x_train,y_train)
print(sv_clf.score(tfid_x_test,y_test))
y_pred=sv_clf.predict(tfid_x_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

0.688
Accuracy: 68.8%


In [33]:
from sklearn.metrics import confusion_matrix,f1_score
confusion_matrix(y_test,y_pred)

array([[2346,  417],
       [ 987,  750]], dtype=int64)

In [34]:
f1score = f1_score(y_test,y_pred)
f1score

0.5165289256198347

In [35]:
def fake_news_det5(news):
    input_data = [news]
    vectorized_input_data = tfvect.transform(input_data)
    prediction = sv_clf.predict(vectorized_input_data)
    print(prediction)

In [36]:
fake_news_det5('pakistan is a country ')

[ True]


In [37]:
#RF
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators = 100) 
rf_clf.fit(tfid_x_train,y_train)
print(rf_clf.score(tfid_x_test,y_test))
y_pred=rf_clf.predict(tfid_x_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

0.6806666666666666
Accuracy: 68.07%


In [38]:
from sklearn.metrics import confusion_matrix,f1_score
confusion_matrix(y_test,y_pred)

array([[2271,  492],
       [ 945,  792]], dtype=int64)

In [39]:
f1score = f1_score(y_test,y_pred)
f1score

0.5243296921549155

In [40]:
def fake_news_det6(news):
    input_data = [news]
    vectorized_input_data = tfvect.transform(input_data)
    prediction = rf_clf.predict(vectorized_input_data)
    print(prediction)

In [41]:
fake_news_det6('donald trumph died')

[False]


In [42]:
#NB
from sklearn.naive_bayes import GaussianNB
tfid_x_test=tfid_x_test.toarray()
tfid_x_train=tfid_x_train.toarray()
nb_clf=GaussianNB()
nb_clf.fit(tfid_x_train,y_train)
print(nb_clf.score(tfid_x_test,y_test))
y_pred=nb_clf.predict(tfid_x_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

0.5557777777777778
Accuracy: 55.58%


In [43]:
from sklearn.metrics import confusion_matrix,f1_score
confusion_matrix(y_test,y_pred)

array([[1259, 1504],
       [ 495, 1242]], dtype=int64)

In [44]:
f1score = f1_score(y_test,y_pred)
f1score

0.5540932411331697

In [45]:
def fake_news_det8(news):
    input_data = [news]
    vectorized_input_data = tfvect.transform(input_data)
    prediction = nb_clf.predict(vectorized_input_data.toarray())
    print(prediction)

In [46]:
fake_news_det8('india is not country')

[ True]


In [47]:
import pickle
pickle.dump(lg_clf,open('lgmodel.pkl', 'wb'))